name = "Booger Aids 6"
author = "Swzo"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60e9c7fd99845c1d596b8517349fe984e419b8a5ab283867bce1094657451a9b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
unsup = "1.2.5"
