name = "Booger Aids 6"
author = ""
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4ec7ea5717f97f8d60e6cef841d6a7eaff0fb1d0cf4dcf40600d6e1e8d3d6b7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
unsup = "1.2.5"
