name = "Booger Aids 6"
author = "Swzo"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85ba4d489e233de2904951ae289c603f77057a281e348b06519788cb6edfd27e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
unsup = "1.2.5"
