[flavor_groups.shaders]
name = "Shaders"
description = "Downloads <b>Iris Shaders</b> + a bunch of popular shader packs"
side = "client"

[[flavor_groups.shaders.choices]]
id = "enable"
name = "Enable"
description = "Download Iris + Shaders"

[[flavor_groups.shaders.choices]]
id = "disable"
name = "Disable"
description = "Fahh no my pc cant handle that shit."

[flavor_groups.world_map_mini_map]
name = "World Map + Mini Map"
description = "Whether to Enable Xaeros world + minimap mods"
side = "both"

[[flavor_groups.world_map_mini_map.choices]]
id = "enable_2"
name = "Enable"

[[flavor_groups.world_map_mini_map.choices]]
id = "disable_2"
name = "Disable"

[metafile."/mods/xaerominimap-neoforge-1-21-1-26-1-0.pw.toml"]
flavors = ["enable_2"]

[metafile."/mods/xaeroworldmap-neoforge-1-21-1-1-41-2.pw.toml"]
flavors = ["enable_2"]
